version: '3.8'

volumes:
  storage:

services:
  influx:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - "DOCKER_INFLUXDB_INIT_MODE=setup"
      - "DOCKER_INFLUXDB_INIT_USERNAME=Administrator"
      - "DOCKER_INFLUXDB_INIT_PASSWORD=thingworxvision"
      - "DOCKER_INFLUXDB_INIT_ORG=PDSVISION"
      - "DOCKER_INFLUXDB_INIT_BUCKET=thingworx"
      - "DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=thingworxvisiontoken"
