version: '2.4'

services:
  platform:
    image: ghcr.io/pdsvision/thingworx-platform-h2:9.3.0
    ports:
      - "80-200:8080"
    environment:
      - "CATALINA_OPTS=-Xms2g -Xmx4g"
      - "ENABLE_HTTP=true"
      - "DATABASE_HOST=postgresql"
      - "DATABASE_PORT=5432"
      - "TWX_DATABASE_SCHEMA=twadmin"
      - "TWX_DATABASE_USERNAME=twadmin"
      - "TWX_DATABASE_PASSWORD=twadmin"
      - "THINGWORX_INITIAL_ADMIN_PASSWORD=${ADMIN_PASSWORD}"
      - "THINGWORX_INITIAL_METRICS_USER_PASSWORD=${METRICS_PASSWORD}"
      - "LS_USERNAME=${LS_USERNAME}"
      - "LS_PASSWORD=${LS_PASSWORD}"
      - "EXTPKG_IMPORT_POLICY_ENABLED=true"
      - "EXTPKG_IMPORT_POLICY_ALLOW_JARRES=true"
      - "EXTPKG_IMPORT_POLICY_ALLOW_JSRES=true"
      - "EXTPKG_IMPORT_POLICY_ALLOW_CSSRES=true"
      - "EXTPKG_IMPORT_POLICY_ALLOW_JSONRES=true"
      - "EXTPKG_IMPORT_POLICY_ALLOW_WEBAPPRES=true"
      - "EXTPKG_IMPORT_POLICY_ALLOW_ENTITIES=true"
      - "EXTPKG_IMPORT_POLICY_ALLOW_EXTENTITIES=true"
