version: '3.8'

services:
  platform:
    image: ghcr.io/pdsvision/thingworx-platform-h2:9.2.7
    ports:
      - "80-200:8080"
    environment:
      - "CATALINA_OPTS=-Xms2g -Xmx4g"
      # NOTE: Set KEYSTORE_PASSWORD (Must match value from security-cli container)
      # NOTE: TWX_DATABASE_USERNAME and TWX_DATABASE_PASSWORD for H2 platform must
      # be set to to create the initial database, or connect to a previous instance.
      - "TWX_DATABASE_USERNAME=admin"
      - "TWX_DATABASE_PASSWORD=admin"
      # NOTE: The following must be set for the Platform to start. This will be
      # the initial Administrator password.
      - "THINGWORX_INITIAL_ADMIN_PASSWORD=thingworxvision"
      # NOTE: The following must be set for the Platform to start. This will be
      # the initial MetricsUser password.
      - "THINGWORX_INITIAL_METRICS_USER_PASSWORD=thingworxvision"
      #Uncomment the below to automatically download license
      #- "LS_USERNAME=${PTCUSERNAME}"
      #- "LS_PASSWORD=${PTCPASSWORD}"
      - "EXTPKG_IMPORT_POLICY_ENABLED=true"
      - "EXTPKG_IMPORT_POLICY_ALLOW_JARRES=true"
      - "EXTPKG_IMPORT_POLICY_ALLOW_JSRES=true"
      - "EXTPKG_IMPORT_POLICY_ALLOW_CSSRES=true"
      - "EXTPKG_IMPORT_POLICY_ALLOW_JSONRES=true"
      - "EXTPKG_IMPORT_POLICY_ALLOW_WEBAPPRES=true"
      - "EXTPKG_IMPORT_POLICY_ALLOW_ENTITIES=true"
      - "EXTPKG_IMPORT_POLICY_ALLOW_EXTENTITIES=true"
      #SSL Configuration
      - "ENABLE_HTTP=true"
      #- "ENABLE_HTTPS=true"
      ## NOTE: If supplying a keystore for SSL, you must set your keystore password
      #- "SSL_KEYSTORE_PASSWORD="
    # Use this to mount your orgs licence file, if not ThingWorx will fallback to temporary licence
    #volumes:
    #  - storage:/ThingworxStorage
    #Use this to mount a custom licence.bin, place the license.bin in the same directory as this file
    #  - C:/Docker/ThingWorx/Platform:/ThingworxPlatform
    #  - C:/Docker/ThingWorx/Storage:/ThingworxStorage
