version: '3.8'

volumes:
  storage:
services:
  postgresql:
    image: ghcr.io/pdsvision/thingworx-platform-postgres-db:9.1.1
    ports:
      - "5432"
    healthcheck:
      test: pg_isready -U postgres
      interval: 15s
    environment:
      # NOTE: Set POSTGRES_USER, POSTGRES_PASSWORD POSTGRES_DB for connecting
      # to the postgres as super user
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=postgres"
      # NOTE: Set TWX_DATABASE_USERNAME, TWX_DATABASE_PASSWORD TWX_DATABASE_SCHEMA for
      # the thingworx database setup that will be created in this database.
      - "TWX_DATABASE_USERNAME=twadmin"
      - "TWX_DATABASE_SCHEMA=twadmin"
      - "TWX_DATABASE_PASSWORD=twadmin"

  platform:
    image: ghcr.io/pdsvision/thingworx-platform-postgres:9.1.1
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - "80-200:8080"
    environment:
      - "CATALINA_OPTS=-Xms2g -Xmx4g"
      - "ENABLE_HTTP=true"
      - "DATABASE_HOST=postgresql"
      - "DATABASE_PORT=5432"
      - "DATABASE_ADMIN_USERNAME=postgres"
      - "DATABASE_ADMIN_PASSWORD=postgres"
      - "DATABASE_ADMIN_SCHEMA=postgres"
      # NOTE: Set TWX_DATABASE_USERNAME, TWX_DATABASE_PASSWORD TWX_DATABASE_SCHEMA for
      # the thingworx database setup that will either be created by the docker image,
      # or connected to if it already exists.
      - "TWX_DATABASE_USERNAME=twadmin"
      - "TWX_DATABASE_SCHEMA=twadmin"
      - "TWX_DATABASE_PASSWORD=twadmin"
      - "THINGWORX_INITIAL_ADMIN_PASSWORD=${ADMIN_PASSWORD}"
      - "THINGWORX_INITIAL_METRICS_USER_PASSWORD=${METRICS_PASSWORD}"
      - "LS_USERNAME=${LS_USERNAME}"
      - "LS_PASSWORD=${LS_PASSWORD}"
      - "EXTPKG_IMPORT_POLICY_ENABLED=true"
      - "EXTPKG_IMPORT_POLICY_ALLOW_JARRES=true"
      - "EXTPKG_IMPORT_POLICY_ALLOW_JSRES=true"
      - "EXTPKG_IMPORT_POLICY_ALLOW_CSSRES=true"
      - "EXTPKG_IMPORT_POLICY_ALLOW_JSONRES=true"
      - "EXTPKG_IMPORT_POLICY_ALLOW_WEBAPPRES=true"
      - "EXTPKG_IMPORT_POLICY_ALLOW_ENTITIES=true"
      - "EXTPKG_IMPORT_POLICY_ALLOW_EXTENTITIES=true"
